### ISSUE TITLE
Generate report template via Go program

### ISSUE THREAD

**Issue by bryanhuhta** [grafana/hackathon-2024-08-pyrobench#6]
In https://github.com/grafana/hackathon-2024-08-pyrobench/issues/3, I hacked together a test report that can be added to a PR via a comment.

In practice, it's pretty sketchy, as it requires downloading a JS file, slurping some relevant data from another step via stdout, and the doing a bunch of parsing in JavaScript. We can significantly simplify this process by doing all the templating in the Go program, then outputting the template to a well-known location (either a file or stdout).  Another step can then pick up this template and handle writing it into a comment.

This will make the template generation more testable and reduce complexity by sharing a lot of components the Go program already uses to run the benchmarks.

**Comment by simonswine** [comment]
We have a reporter now in go
